console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
  template = '❯ '
  foreground = 'darkGray'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  foreground_templates = ['{{if gt .Code 0}}lightRed{{end}}', '{{if eq .Code 0}}lightCyan{{end}}']
  background = 'transparent'
  newline = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  # [[blocks.segments]]
  #   type = 'session'
  #   template = '{{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }} '
  #   style = 'plain'
  #   foreground = 'white'
  #   background = 'transparent'

  [[blocks.segments]]
    type = 'path'
    template = '<b>{{ path .Path .Location }}</b> '
    style = 'plain'
    foreground = 'cyan'
    background = 'transparent'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    template = '{{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    style = 'plain'
    foreground = 'green'
    background = 'transparent'
    foreground_templates = [
		'{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}',
		'{{ if and (gt .Ahead 0) (gt .Behind 0) }}red{{ end }}',
		'{{ if gt .Ahead 0 }}lightMagenta{{ end }}',
		'{{ if gt .Behind 0 }}magenta{{ end }}']

    [blocks.segments.properties]
      branch_template = '{{ trunc 25 .Branch }}'
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'root'
    template = '  '
    style = 'plain'
    foreground = 'white'
    background = 'transparent'

[[blocks]]
  type = 'prompt'
  overflow = 'hide'
  alignment = 'right'

  [[blocks.segments]]
    type = 'status'
    template = '{{ if gt .Code 0 }}{{ else }}{{ end }}  '
    style = 'plain'
    foreground = 'green'
    background = 'transparent'
    foreground_templates = ['{{ if gt .Code 0 }}red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    type = 'node'
    template = ' '
    style = 'plain'
    foreground = 'green'
    background = 'transparent'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false

  [[blocks.segments]]
    type = 'go'
    template = ' '
    style = 'plain'
    foreground = 'blue'
    background = 'transparent'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = 'python'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'

    [blocks.segments.properties]
      display_mode = 'environment'
      fetch_version = false
      fetch_virtual_env = true

  [[blocks.segments]]
    type = 'shell'
    template = 'in <blue>{{ .Name }}</>'
    style = 'plain'
    foreground = 'white'
    background = 'transparent'

  [[blocks.segments]]
    type = 'executiontime'
    template = ' took <yellow>{{ .FormattedMs }}</>'
    style = 'plain'
    foreground = 'white'
    background = 'transparent'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 3000


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}lightRed{{end}}', '{{if eq .Code 0}}lightCyan{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
