console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

# [palette]
#   black = '#262B44'
#   blue = '#4B95E9'
#   green = '#59C9A5'
#   orange = '#F07623'
#   red = '#D81E5B'
#   white = '#E0DEF4'
#   yellow = '#F3AE35'

[palette]
  black = 'black'
  blue = 'blue'
  green = 'green'
  orange = '#C9826B'
  red = 'red'
  white = 'white'
  yellow = 'yellow'
  magenta = 'magenta'
  cyan = 'cyan'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:cyan'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}cyan{{end}}']
  background = 'transparent'
  newline = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  # [[blocks.segments]]
  #   type = 'session'
  #   template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }} '
  #   style = 'plain'
  #   foreground = 'p:white'
  #   background = 'transparent'

  [[blocks.segments]]
    type = 'path'
    template = '<b>{{ path .Path .Location }}</b> '
    style = 'plain'
    foreground = 'p:cyan'
    background = 'transparent'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    template = '{{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    style = 'plain'
    foreground = 'p:green'
    background = 'transparent'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']

    [blocks.segments.properties]
      branch_template = '{{ trunc 25 .Branch }}'
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'root'
    template = '  '
    style = 'plain'
    foreground = 'p:white'
    background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'status'
    template = '{{ if gt .Code 0 }}{{ else }}{{ end }}  '
    style = 'plain'
    foreground = 'p:green'
    background = 'transparent'
    foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    type = 'node'
    template = ' '
    style = 'plain'
    foreground = 'p:green'
    background = 'transparent'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false

  [[blocks.segments]]
    type = 'go'
    template = ' '
    style = 'plain'
    foreground = 'p:blue'
    background = 'transparent'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = 'python'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'

    [blocks.segments.properties]
      display_mode = 'environment'
      fetch_version = false
      fetch_virtual_env = true

  [[blocks.segments]]
    type = 'shell'
    template = 'in <p:blue>{{ .Name }}</>'
    style = 'plain'
    foreground = 'p:white'
    background = 'transparent'

  [[blocks.segments]]
    type = 'executiontime'
    template = ' took <p:yellow>{{ .FormattedMs }}</>'
    style = 'plain'
    foreground = 'p:white'
    background = 'transparent'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 3000


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}cyan{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
