console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

# [palette]
#   black = '#262B44'
#   blue = '#4B95E9'
#   green = '#59C9A5'
#   orange = '#F07623'
#   red = '#D81E5B'
#   white = '#E0DEF4'
#   yellow = '#F3AE35'

[palette]
  black = 'black'
  blue = 'blue'
  green = 'green'
  orange = '#C9826B'
  red = 'red'
  white = 'white'
  yellow = 'yellow'
  magenta = 'magenta'
  cyan = 'cyan'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:cyan'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}cyan{{end}}']
  background = 'transparent'
  newline = true

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    trailing_diamond = ''
    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }} '
    foreground = 'p:black'
    background = 'p:white'
    type = 'session'
    style = 'diamond'

  [[blocks.segments]]
    template = ' {{ path .Path .Location }} '
    foreground = 'p:black'
    powerline_symbol = ''
    background = 'p:cyan'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      style = 'mixed'

  [[blocks.segments]]
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'p:black'
    powerline_symbol = ''
    background = 'p:green'
    type = 'git'
    style = 'powerline'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}', '{{ if gt .Ahead 0 }}p:white{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']

    [blocks.segments.properties]
      branch_template = '{{ trunc 25 .Branch }}'
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = '  '
    foreground = 'p:white'
    powerline_symbol = ''
    background = 'p:yellow'
    type = 'root'
    style = 'powerline'

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    template = ' '
    foreground = 'p:green'
    background = 'transparent'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false

  [[blocks.segments]]
    template = ' '
    foreground = 'p:blue'
    background = 'transparent'
    type = 'go'
    style = 'plain'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    template = ' '
    foreground = 'p:yellow'
    background = 'transparent'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false
      fetch_virtual_env = false

  [[blocks.segments]]
    template = 'in <p:blue><b>{{ .Name }}</b></> '
    foreground = 'p:white'
    background = 'transparent'
    type = 'shell'
    style = 'plain'


  [[blocks.segments]]
    template = ' {{ .FormattedMs }} '
    leading_diamond = ''
    background = 'p:yellow'
    foreground = 'p:black'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 3000

  [[blocks.segments]]
    leading_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
    foreground = 'p:white'
    background = 'p:blue'
    type = 'status'
    style = 'diamond'
    background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}cyan{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
