version = 3

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = '╭─'
    template = '{{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }} '
    foreground = '#4C566A'
    background = '#E5E9F0'
    type = 'session'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  </>{{ .Path }} '
    foreground = '#2E3440'
    powerline_symbol = ''
    background = '#81A1C1'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'folder'

  [[blocks.segments]]
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#2E3440'
    powerline_symbol = ''
    background = '#A3BE8C'
    type = 'git'
    style = 'powerline'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#D08770{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#EBCB8B{{ end }}', '{{ if gt .Ahead 0 }}#B48EAD{{ end }}', '{{ if gt .Behind 0 }}#B48EAD{{ end }}']

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = '  {{ .FormattedMs }} '
    foreground = '#2E3440'
    powerline_symbol = ''
    background = '#B48EAD'
    type = 'executiontime'
    style = 'powerline'

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    template = ' {{ if gt .Code 0 }} {{ reason .Code }}{{ else }} {{ end }} '
    foreground = '#2E3440'
    background = '#EBCB8B'
    type = 'status'
    style = 'diamond'

    [blocks.segments.properties]
      always_enabled = true
      background_templates = ['{{ if gt .Code 0 }}#f1184c{{ end }}']
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = ' {{ .Name }} </>'
    foreground = '#2E3440'
    powerline_symbol = ''
    background = '#D08770'
    type = 'shell'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}  '
    foreground = '#242424'
    powerline_symbol = ''
    background = '#A3BE8C'
    type = 'battery'
    style = 'powerline'
    background_templates = ['{{if eq "Charging" .State.String}}#A3BE8C{{end}}', '{{if eq "Discharging" .State.String}}#A3BE8C{{end}}', '{{if eq "Full" .State.String}}#A3BE8C{{end}}']
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    trailing_diamond = ''
    template = '  {{ .CurrentDate | date .Format }} '
    foreground = '#2E3440'
    background = '#81A1C1'
    type = 'time'
    style = 'diamond'
    invert_powerline = true

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╰─'
    foreground = '#ECEFF4'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<#B48EAD>❯</><#A3BE8C>❯</><#EBCB8B>❯</> '
    foreground = '#8FBCBB'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#ef5350{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'
